### ISSUE TITLE
adds factory_girl gem to rails apps but current recommended gem is factory_girl_rails

### ISSUE THREAD

**Issue by KellyRedWill** [LaunchAcademy/make_it_so#6]
All searching I can find recommends `factory_girl_rails` and our reading on FactoryGirl also references `factory_girl_rails`. Currently make_it_so adds and sets up `factory_girl` instead. Maybe this should be changed?

**Comment by dpickett** [comment]
Thanks for the suggestion. I'm not a huge fan of the `factory_bot` generators - it generates a separate file per model, which I don't think is ideal. Closing for now.
